-- MySQL Script generated by MySQL Workbench
-- Mon Mar  5 23:18:08 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SSMDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SSMDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SSMDB` DEFAULT CHARACTER SET utf8 ;
USE `SSMDB` ;

-- -----------------------------------------------------
-- Table `SSMDB`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SSMDB`.`Role` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `RoleName` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SSMDB`.`Account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SSMDB`.`Account` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `LoginName` VARCHAR(45) NULL,
  `Password` VARCHAR(45) NULL,
  `UserId` INT NULL,
  `LastLoginDateTime` DATETIME NULL,
  `Role_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Account_Role_idx` (`Role_Id` ASC),
  CONSTRAINT `fk_Account_Role`
    FOREIGN KEY (`Role_Id`)
    REFERENCES `SSMDB`.`Role` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SSMDB`.`Teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SSMDB`.`Teacher` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `TeacherName` VARCHAR(45) NULL,
  `TeacherNO` VARCHAR(45) NULL,
  `Email` VARCHAR(60) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SSMDB`.`School`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SSMDB`.`School` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `SchoolName` VARCHAR(45) NULL,
  `Province` VARCHAR(45) NULL,
  `City` VARCHAR(45) NULL,
  `Address` VARCHAR(120) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `SSMDB`.`Specialty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SSMDB`.`Specialty` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `SpecialtyName` VARCHAR(45) NULL,
  `School_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Specialty_School1_idx` (`School_Id` ASC),
  CONSTRAINT `fk_Specialty_School1`
    FOREIGN KEY (`School_Id`)
    REFERENCES `SSMDB`.`School` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SSMDB`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SSMDB`.`Student` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `StudentName` VARCHAR(45) NULL,
  `StudentNO` VARCHAR(45) NULL,
  `CreateTime` DATETIME NULL,
  `School_Id` INT NOT NULL,
  `Specialty_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Student_School1_idx` (`School_Id` ASC),
  INDEX `fk_Student_Specialty1_idx` (`Specialty_Id` ASC),
  CONSTRAINT `fk_Student_School1`
    FOREIGN KEY (`School_Id`)
    REFERENCES `SSMDB`.`School` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Student_Specialty1`
    FOREIGN KEY (`Specialty_Id`)
    REFERENCES `SSMDB`.`Specialty` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SSMDB`.`Classes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SSMDB`.`Classes` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `ClassesName` VARCHAR(45) NULL,
  `School_Id` INT NOT NULL,
  `Specialty_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Classes_School1_idx` (`School_Id` ASC),
  INDEX `fk_Classes_Specialty1_idx` (`Specialty_Id` ASC),
  CONSTRAINT `fk_Classes_School1`
    FOREIGN KEY (`School_Id`)
    REFERENCES `SSMDB`.`School` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Classes_Specialty1`
    FOREIGN KEY (`Specialty_Id`)
    REFERENCES `SSMDB`.`Specialty` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SSMDB`.`UserAction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SSMDB`.`UserAction` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `UserActionName` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SSMDB`.`Role_has_UserAction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SSMDB`.`Role_has_UserAction` (
  `Role_Id` INT NOT NULL,
  `UserAction_Id` INT NOT NULL,
  PRIMARY KEY (`Role_Id`, `UserAction_Id`),
  INDEX `fk_Role_has_UserAction_UserAction1_idx` (`UserAction_Id` ASC),
  INDEX `fk_Role_has_UserAction_Role1_idx` (`Role_Id` ASC),
  CONSTRAINT `fk_Role_has_UserAction_Role1`
    FOREIGN KEY (`Role_Id`)
    REFERENCES `SSMDB`.`Role` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Role_has_UserAction_UserAction1`
    FOREIGN KEY (`UserAction_Id`)
    REFERENCES `SSMDB`.`UserAction` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SSMDB`.`Student_has_Classes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SSMDB`.`Student_has_Classes` (
  `Student_Id` INT NOT NULL,
  `Classes_Id` INT NOT NULL,
  PRIMARY KEY (`Student_Id`, `Classes_Id`),
  INDEX `fk_Student_has_Classes_Classes1_idx` (`Classes_Id` ASC),
  INDEX `fk_Student_has_Classes_Student1_idx` (`Student_Id` ASC),
  CONSTRAINT `fk_Student_has_Classes_Student1`
    FOREIGN KEY (`Student_Id`)
    REFERENCES `SSMDB`.`Student` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Student_has_Classes_Classes1`
    FOREIGN KEY (`Classes_Id`)
    REFERENCES `SSMDB`.`Classes` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SSMDB`.`Course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SSMDB`.`Course` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `CourseName` VARCHAR(45) NULL,
  `CourseNO` VARCHAR(45) NULL,
  `TotalScore` INT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SSMDB`.`Specialty_has_Course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SSMDB`.`Specialty_has_Course` (
  `Specialty_Id` INT NOT NULL,
  `Course_Id` INT NOT NULL,
  PRIMARY KEY (`Specialty_Id`, `Course_Id`),
  INDEX `fk_Specialty_has_Course_Course1_idx` (`Course_Id` ASC),
  INDEX `fk_Specialty_has_Course_Specialty1_idx` (`Specialty_Id` ASC),
  CONSTRAINT `fk_Specialty_has_Course_Specialty1`
    FOREIGN KEY (`Specialty_Id`)
    REFERENCES `SSMDB`.`Specialty` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Specialty_has_Course_Course1`
    FOREIGN KEY (`Course_Id`)
    REFERENCES `SSMDB`.`Course` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SSMDB`.`EvaluationModule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SSMDB`.`EvaluationModule` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `EvaluationModuleName` VARCHAR(45) NULL,
  `PaarentId` INT NULL,
  `Score` INT NULL,
  `Percent` INT NULL,
  `Flag` TINYINT NULL,
  `UserId` INT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SSMDB`.`CourseAssign`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SSMDB`.`CourseAssign` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `TeacherId` INT NULL,
  `ClassId` INT NULL,
  `RootEvaluationModuleId` INT NULL,
  `Course_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_CourseAssign_Course1_idx` (`Course_Id` ASC),
  CONSTRAINT `fk_CourseAssign_Course1`
    FOREIGN KEY (`Course_Id`)
    REFERENCES `SSMDB`.`Course` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SSMDB`.`Specialty_MainEvaluation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SSMDB`.`Specialty_MainEvaluation` (
  `SpecialtyId` INT NULL,
  `EvaluationModuleId` INT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SSMDB`.`SignIn`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SSMDB`.`SignIn` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `SignInName` VARCHAR(45) NULL,
  `OpenTime` DATETIME NULL,
  `CourseAssign_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_SignIn_CourseAssign1_idx` (`CourseAssign_Id` ASC),
  CONSTRAINT `fk_SignIn_CourseAssign1`
    FOREIGN KEY (`CourseAssign_Id`)
    REFERENCES `SSMDB`.`CourseAssign` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SSMDB`.`Grade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SSMDB`.`Grade` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `ModuleId` INT NULL,
  `StudentId` INT NULL,
  `Score` DOUBLE NULL,
  `Course_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Grade_Course1_idx` (`Course_Id` ASC),
  CONSTRAINT `fk_Grade_Course1`
    FOREIGN KEY (`Course_Id`)
    REFERENCES `SSMDB`.`Course` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SSMDB`.`SignInType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SSMDB`.`SignInType` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `SignInTypeName` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SSMDB`.`Sign_Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SSMDB`.`Sign_Student` (
  `StudentId` INT NULL,
  `StudentName` VARCHAR(45) NULL,
  `SignInType_Id` INT NOT NULL,
  `SignIn_Id` INT NOT NULL,
  INDEX `fk_Sign_Student_SignInType1_idx` (`SignInType_Id` ASC),
  INDEX `fk_Sign_Student_SignIn1_idx` (`SignIn_Id` ASC),
  CONSTRAINT `fk_Sign_Student_SignInType1`
    FOREIGN KEY (`SignInType_Id`)
    REFERENCES `SSMDB`.`SignInType` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sign_Student_SignIn1`
    FOREIGN KEY (`SignIn_Id`)
    REFERENCES `SSMDB`.`SignIn` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
