package com.ietscode.entity;

import java.util.Date;

public class Appointment extends AppointmentKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.appoint_time
     *
     * @mbg.generated Sun Feb 25 23:14:44 CST 2018
     */
    private Date appointTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.appoint_time
     *
     * @return the value of appointment.appoint_time
     *
     * @mbg.generated Sun Feb 25 23:14:44 CST 2018
     */
    public Date getAppointTime() {
        return appointTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.appoint_time
     *
     * @param appointTime the value for appointment.appoint_time
     *
     * @mbg.generated Sun Feb 25 23:14:44 CST 2018
     */
    public void setAppointTime(Date appointTime) {
        this.appointTime = appointTime;
    }
}